### ISSUE TITLE
Products MVP Complete

### ISSUE THREAD

**Issue by SouVangLee** [SouVangLee/FishNGames#8]
I am ready to get my Products MVP checked.

**Comment by SouVangLee** [comment]
- [x] Each product should be displayed in its category.
- [x] Each product should have its own show page.
- [x] Render popular items with images on Splash page.
- [x] Render categories with images on Splash page.
- [x] Each product should have an image.
- [x] Each product should have a description.
- [x] Each product should have a title.
- [x] Each product should have a price.

**Comment by Vanchen07** [comment]
Wow, this looks great!!
